name: "Checkly Deployment"
description: "Run and deploy Checkly tests"

inputs:
  private-location-name:
    description: "Name of the Checkly private location"
    required: true
  checkly-api-key:
    description: "Checkly API key"
    required: true
  checkly-accountid:
    description: "Api keyCheckly account id
    required: true
  config-path:
    description: "Path to the Checkly configuration file"
    default: "checkly.config.ts"
    required: false
  main-branch-name:
    description: "Name of the main branch"
    default: "refs/heads/main"
    required: false

runs:
  using: "composite"
  steps:
    - name: Test Checks
      shell: pwsh
      run: |
        npm i --save-dev checkly ts-node typescript

        echo 'Fetching environment variables...'
        npx checkly env pull env.prod 

        echo 'Running Checkly tests...'
        npx checkly test --verbose --record --reporter ci --private-location ${{ inputs.private-location-name }} --config="${{ github.workspace }}/${{ inputs.config-path }}" --env-file ./env.prod
        
        echo 'Previewing the changes...'
        npx checkly deploy --preview --config="${{ github.workspace }}/${{ inputs.config-path }}"
      env:
        CHECKLY_API_KEY: ${{ inputs.checkly-api-key }}
        CHECKLY_ACCOUNT_ID: ${{ inputs.checkly-accountid }}
        CHECKLY_REPO_BRANCH: ${{ github.ref }}

    - name: Deploy to Checkly
      if: ${{ success() && github.ref == inputs.main-branch-name }}
      shell: pwsh
      run: |
        npx checkly deploy --force --config="${{ github.workspace }}/${{ inputs.config-path }}"
      env:
        CHECKLY_API_KEY: ${{ inputs.checkly-api-key }}
        CHECKLY_ACCOUNT_ID: ${{ inputs.checkly-accountid }}
        CHECKLY_REPO_BRANCH: ${{ github.ref }}