name: "Extract potential Jira issues from branch"
description: "Extracts potential Jira issue numbers from branch name using the official pattern"
inputs:
  branch_name:
    description: "The branch name to extract Jira issue numbers from"
    required: true
outputs:
  jira_issue_matches:
    description: "The extracted potential Jira issue numbers"
    value: ${{ steps.extract.outputs.jira_issue_matches }}
  matches:
    description: "Whether the branch name matches the Jira pattern"
    value: ${{ steps.extract.outputs.matches }}
  pattern:
    description: "The regex pattern used for Jira validation"
    value: ${{ steps.extract.outputs.pattern }}

runs:
  using: "composite"
  steps:
    - name: Extract Jira Issue
      id: extract
      shell: pwsh
      run: |
        $BranchPattern = '\b(?!revert-\d+\b)[A-Za-z][A-Za-z0-9]+-\d+'
        $BranchName = "${{ inputs.branch_name }}"

        Write-Host "Branch name: $BranchName"
        Write-Host "Pattern: $BranchPattern"

        # Test the pattern match
        $jiraIssueMatches = [regex]::Matches($BranchName, $BranchPattern)

        if ($jiraIssueMatches.Count -gt 0) {
          $matches = "true"
          Write-Host "✅ Match found: $jiraIssueMatches"
         } else {
          $jiraIssueMatches = @()

          $matches = "false"
          Write-Host "❌ No match found"
        }

        # Set outputs
        $jsonJiraMatches = $jiraIssueMatches | ForEach-Object { $_.Value } | ConvertTo-Json -Compress -AsArray
        "jira_issue_matches=$jsonJiraMatches" >> $env:GITHUB_OUTPUT
        "matches=$matches" >> $env:GITHUB_OUTPUT
        "pattern=$BranchPattern" >> $env:GITHUB_OUTPUT
