name: "Retrieve a managed secret"
description: "This action retrieves a secret from an Azure Key Vault."

inputs:
  azure-client-id:
    description: "The Azure client ID"
    required: true
  azure-tenant-id:
    description: "The Azure tenant ID"
    required: true
  azure-subscription-id:
    description: "The Azure subscription ID"
    required: true
  keyvault-name:
    description: "The Azure Key Vault name"
    required: true
  secret-name:
    description: "The name of the secret to retrieve"
    required: true

outputs:
  secret:
    description: "The retrieved secret (masked)"
    value: ${{ steps.get_secret.outputs.masked_secret }}

runs:
  using: "composite"
  steps:
    - name: Validate variables are available
      shell: pwsh
      env:
        clientId: ${{ inputs.azure-client-id }}
        tenantId: ${{ inputs.azure-tenant-id }}
        subscriptionId: ${{ inputs.azure-subscription-id }}
      run: |
        $IsValid = $env:clientId -and $env:tenantId -and $env:subscriptionId
        if (-not $IsValid) {
          Write-Error @"
        Required inputs are not set. Please provide 'azure-client-id', 'azure-tenant-id', and 'azure-subscription-id'.
        Documentation to configure the repository: https://workleap.atlassian.net/wiki/spaces/TL/pages/5211226436
        "@
          exit 1
        }

    - name: 'Azure CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: Get Secrets from Azure Key Vault
      id: get_secret
      shell: bash
      run: |
        secret_value=$(az keyvault secret show --vault-name "${{ inputs.keyvault-name }}" --name "${{ inputs.secret-name }}" --query value -o tsv)
        echo "::add-mask::$secret_value"
        echo "masked_secret=$secret_value" >> $GITHUB_OUTPUT
