name: Jira

on:
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  call-workflow-jira:
    uses: ./.github/workflows/reusable-jira-workflow.yml
    with:
      reusable_workflows_ref: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
