name: Jira

on:
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  call-workflow-jira:
    uses: ./.github/workflows/reusable-jira-workflow.yml
    with:
      branch_name: ${{ github.head_ref }}
    permissions:
      id-token: write
      contents: read

  test:
    runs-on: [idp]    
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: workleap/wl-reusable-workflows/.github/workflows/reusable-jira-workflow.yml@feature/FENG-573
        with:
          private-location-name: dummy
          api-key: dummy
          account-id: dummy
