name: Jira

on:
  pull_request:
  push:


jobs:
  test:
    runs-on: [idp]    
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: workleap/wl-reusable-workflows/.github/workflows/reusable-jira-workflow.yml@feature/FENG-573
        with:
          private-location-name: dummy
          api-key: dummy
          account-id: dummy
