name: Jira

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  main:
    runs-on: [self-hosted, idp]
    steps:
    - name: 'Azuze CLI login'
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    - name: Get Secrets from Azure Key Vault
      id: get_secrets
      run: |
        # Set env.JIRA_TOKEN
        JIRA_TOKEN=$(az keyvault secret show --vault-name ${{ vars.IDP_CICD_KEYVAULT_NAME }} --name "jira-token" --query value -o tsv)
        echo "jira_token=$JIRA_TOKEN" >> $GITHUB_OUTPUT

    - name: Check Jira Story
      shell: pwsh
      run: |
            Install-Module JiraPS -Scope CurrentUser -Force
            if ("${{ inputs.branch_name }}" -like "*renovate/*" -eq $True)
            {
              Write-Host "Skipping, renovate branch detected"
              return
            }

            Set-JiraConfigServer -Server "${{ secrets.JIRA_URL }}"
            if("${{ inputs.branch_name }}" -match "(?<=\/)[a-zA-Z][a-zA-Z0-9]*[_-][0-9]+" -eq $False)
            {
              throw "Branch name ${{ inputs.branch_name }} doesn't respect the required pattern ((?<=\/)[a-zA-Z][a-zA-Z0-9]*[_-][0-9]+). A valid branch name example would be: feature/IDP-123"
            }

            $JiraIssueKey = $Matches[0]
            $PWord = ConvertTo-SecureString -String "${{ steps.get_secrets.outputs.jira_token }}" -AsPlainText -Force
            $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "${{ secrets.JIRA_USERNAME }}", $PWord

            Write-Host "Retrieving Jira issue with number $JiraIssueKey"
            Get-JiraIssue -Key $JiraIssueKey -Credential $Credential -ErrorAction Stop | out-null
            Write-Host "Successfully retrieved Jira issue"
