name: Create stable release

on:
  schedule:
    - cron: "0 3 * * *" # Daily at 03:00
  workflow_dispatch:

jobs:
  create-release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/create-stable-release.yml
