name: Create stable release

on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  workflow_dispatch:

jobs:
  create-release:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/create-stable-release.yml