name: Terraform Auto Documentation
on: workflow_call

jobs:
  terraform-auto-doc:
    name: Terraform auto documentation
    runs-on: [idp]
    permissions:
      contents: write
    continue-on-error: true
    steps:     
      - name: Authenticate with GitHub App
        id: auth
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TERRAFORM_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.TERRAFORM_AUTOMATION_PRIVATE_KEY }}     

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          fetch-depth: 0
          token: ${{ steps.auth.outputs.token }}

      - name: Terraform Docs
        run: terraform-docs markdown table --output-file README.md --hide resources,data-sources .

      - name: Commit file updates
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          default_author: github_actions
          message: 'chore: update terraform documentation'
          push: true
          fetch: true
          pull: '--no-rebase'